---
name: 'Gitlab CI Pipeline Trigger'
description: ''
author: 'SIMP Team'
inputs:
  gitlab_group:
    description: TODO
    required: true
    default: ${{ github.event.organization.login }}
  github_repository:
    description: TODO
    required: true
    default: ${{ github.ref }}
  github_repository_owner:
    description: TODO
    required: true
    default: ${{ github.repository_owner }}
  git_branch:
    description: TODO
    required: true
    default: TODO
  gitlab_api_private_token:
    description: TODO
    required: true
  target_hashref:
    description: TODO
    required: true
    default: TODO
  gitlab_server_url:
    description: TODO
    required: false
    default: 'https://gitlab.com'
  gitlab_api_url:
    description: TODO
    required: false
    default: 'https://gitlab.com/api/v4'
branding:
  icon: gitlab
  color: green

runs:
  using: "composite"

  steps:
    - name: Trigger CI
      shell: bash
      env:
        GIT_BRANCH: ${{ inputs.git_branch }}
        GITLAB_GROUP: ${{ inputs.gitlab_group }}
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        GITHUB_REPOSITORY_OWNER: ${{ inputs.github_repository_owner }}
        GITLAB_API_PRIVATE_TOKEN: ${{ inputs.gitlab_api_private_token }}
        GET_HASHREF: ${{ inputs.target_hashref }}
        GITLAB_SERVER_URL: ${{ inputs.gitlab_server_url }}
        GITLAB_API_URL: ${{ inputs.gitlab_api_url }}
        TARGET_HASHREF: ${{ inputs.target_hashref }}
      run: ${{ github.action_path }}/trigger_glci_pipeline.bash

